---
title: "GPpaymentGraphs"
output: word_document
date: "2025-11-11"
---

```{r load-imd}
library(tidyverse)
library(readxl)

# load IMD data and calculated a re-weighted IMD for 2021 LSOA codes using the 2011-2021 lookup

imd_raw <- read_csv(file="data/File_7_-_All_IoD2019_Scores__Ranks__Deciles_and_Population_Denominators_3.csv", name_repair = make.names)

#colnames(imd_raw)
imd <- imd_raw %>%
  rename(
    LSOA_CODE = LSOA.code..2011.,
    IMD_SCORE = Index.of.Multiple.Deprivation..IMD..Score,
    IMD_DECILE = Index.of.Multiple.Deprivation..IMD..Decile..where.1.is.most.deprived.10..of.LSOAs.,
    IMD_HEALTH = Health.Deprivation.and.Disability.Score) %>%
  mutate(
    IMD_QUINTILE = case_when(IMD_DECILE %in% c(1:2) ~ 1,
                             IMD_DECILE %in% c(3:4) ~ 2,
                             IMD_DECILE %in% c(5:6) ~ 3,
                             IMD_DECILE %in% c(7:8) ~ 4,
                             IMD_DECILE %in% c(9:10) ~ 5),
    LSOA_DATE = 2011) %>%
  select(LSOA_CODE, IMD_SCORE, IMD_HEALTH, IMD_QUINTILE, LSOA_DATE)

mapping <- read_csv(file = "data/LSOA_2011_to_LSOA_2021_Lookup_E_W.csv", name_repair = make.names)

# convert 2021 LSOA groups if the LSOA CHNGID M (merged in 2021) or X (unclear mapping)

weighted_mapping = mapping %>% left_join(
  mapping %>% filter(CHGIND=="M" | CHGIND=="X") %>%
    group_by(LSOA21CD) %>%
    summarise(WEIGHT=1/n())) %>%
  mutate(WEIGHT=if_else(CHGIND %in% c("S","U"),1,WEIGHT))


weighted_imd <- weighted_mapping  %>%
  left_join(select(imd, LSOA_CODE, IMD_HEALTH, IMD_SCORE), by=c("LSOA11CD" = "LSOA_CODE")) %>%
  mutate(
    weighted_imd = IMD_SCORE*WEIGHT,
    weighted_imd_health = IMD_HEALTH*WEIGHT
  ) %>%
  group_by(LSOA21CD) %>%
  summarise(
    IMD_SCORE = sum(weighted_imd),
    IMD_HEALTH = sum(weighted_imd_health)
  )  %>%
  mutate(IMD_QUINTILE = ntile(-IMD_SCORE,5)) %>%
  mutate(LSOA_DATE = 2021) %>%
  rename(LSOA_CODE = LSOA21CD)

imd_2011_2021 <- rbind(imd, weighted_imd)


year_list <- c(2017:2023)


load_ons_data <- function(year, sex) {
  
  #print(year)
  
  if(year == 2017) {
    object_url = "data/population/SAPE20DT2-mid-2017-lsoa-syoa-estimates-unformatted.xls"
  } else if(year == 2018) {
    object_url = "data/population/SAPE21DT2-mid-2018-lsoa-syoa-estimates-unformatted.xlsx"
  } else if(year == 2019) {
    object_url = "data/population/SAPE22DT2-mid-2019-lsoa-syoa-estimates-unformatted.xlsx"
  } else if(year == 2020) {
    object_url = "data/population/sape23dt2mid2020lsoasyoaestimatesunformatted.xlsx"
  } else if(year == 2021) {
    object_url = "data/population/sapelsoasyoatablefinal.xlsx"
    excel_sheet ="Mid-2021 LSOA 2021"
  } else if(year %in% c(2022:2023)) {
    object_url = "data/population/sapelsoasyoatablefinal.xlsx"
    excel_sheet ="Mid-2022 LSOA 2021"
  } # end setting the object url
  
  print(object_url)
  
  if(year == 2017) {
    
    lsoa_date = 2011
    
    data <- read_xls(
      path = object_url,
      sheet=paste0("Mid-",year," ",sex),
      skip = 4,
      trim_ws=TRUE,
      .name_repair = "universal"
    )
    
    # data <- aws.s3::s3read_using(
    #   FUN = readxl::read_xls,
    #   object = object_url,
    #   bucket = s3_bucket,
    #   sheet=paste0("Mid-",year," ",sex),
    #   skip = 4,
    #   trim_ws=TRUE,
    #   .name_repair = "universal")
    
  } else if(year %in% c(2018:2020)) {
    
    lsoa_date = 2011
    
    data <- read_xlsx(
      path = object_url,
      sheet = paste0("Mid-",year," ",sex),
      skip = 4,
      trim_ws=TRUE,
      .name_repair = "universal"
    )
    
    # data <- aws.s3::s3read_using(
    #   FUN = readxl::read_xlsx,
    #   object = object_url,
    #   bucket = s3_bucket,
    #   sheet=paste0("Mid-",year," ",sex),
    #   skip = 4,
    #   trim_ws=TRUE,
    #   .name_repair = "universal")
    
  } else if(year %in% c(2021:2023)) {
    
    lsoa_date = 2021
    
    data <- read_xlsx(
      path = object_url,
      sheet = excel_sheet,
      skip = 3,
      trim_ws=TRUE,
      .name_repair = "universal"
    )
    
    # data <- aws.s3::s3read_using(
    #   FUN = readxl::read_xlsx,
    #   object = object_url,
    #   bucket = s3_bucket,
    #   sheet = "Mid-2021 LSOA 2021",
    #   skip = 3,
    #   trim_ws=TRUE,
    #   .name_repair = "universal")
    
  } # end loading the data
  
  if(year %in% c(2017:2018)) {
    
    data1 <- data %>%
      select(-All.Ages) %>%
      pivot_longer(cols=!c('Area.Codes', 'Area.Names'), names_to='AGE', values_to='POP') %>%
      mutate(AGE = as.numeric(str_remove_all(AGE, '[^[:alnum:]]')),
             SEX = sex) %>%
      rename(LSOA_CODE = Area.Codes)
    
  } else if(year %in% c(2019:2020)) {
    
    data1 <- data %>%
      select(-contains('Boundaries'), -All.Ages) %>%
      pivot_longer(cols=!c('LSOA.Code', 'LSOA.Name'), names_to='AGE', values_to='POP') %>%
      mutate(AGE = as.numeric(str_remove_all(AGE, '[^[:alnum:]]')),
             SEX = sex) %>%
      rename(LSOA_CODE = LSOA.Code)
    
  } else if (year %in% c(2021:2023)) {
    
    data1 <- data %>%
      select(-c(LAD.2021.Code, LAD.2021.Name, LSOA.2021.Name, Total)) %>%
      pivot_longer(!LSOA.2021.Code, names_to="AGE", values_to="POP") %>%
      separate(AGE, into = c("SEX", "AGE"), sep = "(?<=[A-Za-z])(?=[0-9])") %>%
      mutate(SEX = case_when(SEX == "F" ~ "Females",SEX == "M" ~ "Males")
      ) %>%
      filter(SEX == sex) %>%
      rename(LSOA_CODE = LSOA.2021.Code)
    
  } # end cleaning the data by year
  
  # group into age groups once here
  data2 <- data1 %>%
    mutate(
      AGE = as.numeric(AGE),
      AGE = case_when(
        AGE %in% c(0:4) ~ "0_4",
        AGE %in% c(5:14) ~ "5_14",
        AGE %in% c(15:44) ~ "15_44",
        AGE %in% c(45:64) ~ "45_64",
        AGE %in% c(65:74) ~ "65_74",
        AGE %in% c(75:84) ~ "75_84",
        AGE >85  ~ "85_PLUS")
    ) %>%
    group_by(LSOA_CODE, AGE) %>%
    summarise(Total_POP = sum(POP)) %>%
    mutate(
      YEAR = year,
      SEX = sex,
      LSOA_DATE = lsoa_date
    )
  
}

#ons_data_M <- lapply(year_list, load_ons_data, sex="Males")
#ons_data_F <- lapply(year_list, load_ons_data, sex="Females")

#ons_both <- c(ons_data_M, ons_data_F)
ons_df <- read.csv("ons_population.csv", stringsAsFactors = FALSE)

#ons_df <- as.data.frame(do.call(rbind, ons_both))

## calculate weighted LSOA populations using Carr Hill formula values from 'Level or not?'

adj_pop_df <- ons_df %>%
  mutate(
    SEX = case_when(
      SEX == "Males" ~ "MALE",
      SEX == "Females" ~ "FEMALE"
    ),
    YEAR = as.numeric(YEAR)
  ) %>%
  pivot_wider(
    names_from = c(SEX, AGE),
    values_from = Total_POP
  ) %>%
  filter(!str_detect(LSOA_CODE, 'W')) %>%
  left_join(imd_2011_2021, by=c("LSOA_CODE"="LSOA_CODE", "LSOA_DATE"="LSOA_DATE")) %>%
  group_by(YEAR, LSOA_CODE) %>%
  mutate(TOTAL_POP = MALE_0_4 + 
           MALE_5_14 + 
           MALE_15_44 + 
           MALE_45_64 +
           MALE_65_74 +
           MALE_75_84 +
           MALE_85_PLUS +
           FEMALE_0_4 +
           FEMALE_5_14 +
           FEMALE_15_44 +
           FEMALE_45_64 +
           FEMALE_65_74 +
           FEMALE_75_84 +
           FEMALE_85_PLUS,
         ADJUSTED_POP = (2.354*MALE_0_4 + 
                           1*MALE_5_14 + 
                           0.913*MALE_15_44 + 
                           1.373*MALE_45_64 +
                           2.531*MALE_65_74 +
                           3.254*MALE_75_84 +
                           3.193*MALE_85_PLUS +
                           2.241*FEMALE_0_4 +
                           1.030*FEMALE_5_14 +
                           1.885*FEMALE_15_44 +
                           2.115*FEMALE_45_64 +
                           2.820*FEMALE_65_74 +
                           3.301*FEMALE_75_84 +
                           3.090*FEMALE_85_PLUS)* 1.054^IMD_HEALTH
         
  )

# normalise the adjusted population

adj_pop_norm = adj_pop_df %>% 
  group_by(YEAR) %>%
  summarise(TOTAL = sum(TOTAL_POP), ADJ=sum(ADJUSTED_POP)) %>%
  mutate(AF=TOTAL/ADJ) %>%
  select(YEAR,AF) %>%
  inner_join(adj_pop_df) %>%
  mutate(NORMALISED_ADJ_POP = ADJUSTED_POP*AF) %>%
  select(YEAR,LSOA_CODE,NEED_ADJ_POP=NORMALISED_ADJ_POP,TOTAL_POP)

### load the attribution datasets ###

temp = list.files(path = "data/attribution", pattern="\\.csv$", full.names = TRUE)

lsoa_attributions <- lapply(temp, read.csv)

#lsoa_attributions <- bulk_import_csv_files(iau_bucket, attribution_prefix)

for (i in seq_along(lsoa_attributions)) {
  names(lsoa_attributions[[i]]) <- c("PUBLICATION","EXTRACT_DATE","PRACTICE_CODE","PRACTICE_NAME","LSOA_CODE","SEX","NUMBER_OF_PATIENTS")
}

lsoa_attributions_df <- as.data.frame(do.call(rbind, lsoa_attributions))

lsoa_prac_pc = lsoa_attributions_df %>%
  mutate(YEAR = as.numeric(str_sub(EXTRACT_DATE, start = -4))) %>%
  select(YEAR, PRACTICE_CODE, PRACTICE_NAME, LSOA_CODE, NUMBER_OF_PATIENTS) %>%
  group_by(PRACTICE_CODE, YEAR) %>%
  mutate(total_pat_in_practice = sum(NUMBER_OF_PATIENTS),
         pc = NUMBER_OF_PATIENTS / total_pat_in_practice) %>%
  select(-NUMBER_OF_PATIENTS) %>%
  ungroup() %>%
  mutate(LSOA_DATE = case_when(YEAR<2021 ~ 2011,
                               YEAR>2020 ~2021))

# assign IMD at the practice level using the attributions dataset
prac_imd <- lsoa_prac_pc %>% 
  inner_join(imd_2011_2021, by = c("LSOA_CODE", "LSOA_DATE")) %>% 
  inner_join(adj_pop_norm, by = c("LSOA_CODE", "YEAR")) %>%
  group_by(YEAR, PRACTICE_CODE) %>%
  summarise(
    IMD_SCORE_PROP = sum(pc * TOTAL_POP * IMD_SCORE, na.rm = TRUE),
    total_weighted_pop = sum(pc * TOTAL_POP, na.rm = TRUE),
    total_pat_in_practice = first(total_pat_in_practice)
  ) %>% 
  mutate(
   IMD_SCORE = IMD_SCORE_PROP / total_weighted_pop
  ) %>%
  ungroup() %>%
  select(YEAR, PRACTICE_CODE, IMD_SCORE, total_weighted_pop, total_pat_in_practice)

prac_imd = prac_imd %>% 
  group_by(YEAR) %>%
  arrange(-IMD_SCORE) %>%
 mutate(CUM_POP = cumsum(total_weighted_pop), PROP = CUM_POP/max(CUM_POP),
         IMD_DECILE=cut(PROP,10,labels=FALSE),
         IMD_QUINTILE = ntile(PROP,5)) %>%
  select(YEAR,PRACTICE_CODE,IMD_SCORE,IMD_QUINTILE, total_weighted_pop, total_pat_in_practice )

#write.csv(prac_imd, "Prac_IMD.csv", row.names = FALSE)
```


```{r load-imd}

### load workforce datasets

temp_workforce = list.files(path = "data/workforce", pattern="\\.csv$", full.names = TRUE)

september_records <- temp_workforce %>% str_subset(pattern = "September")


workforce_datasets <-   lapply(
  september_records, function(x) {
    print(x)
    split_path = strsplit(x, " ")
    year = split_path[[1]][[6]]
    workforce <- read.csv(x)
    
    workkforce_relevant_cols <- workforce %>%
      select(PRAC_CODE, PRAC_NAME, TOTAL_GP_FTE, TOTAL_GP_EXTGL_FTE, TOTAL_GP_EXL_FTE, TOTAL_GP_RET_FTE, GP_SOURCE) %>%
      mutate(YEAR = as.numeric(year))
    
  }
)

workforce_df <- as.data.frame(do.call(rbind, workforce_datasets))


attribute_gps_to_lsoa <- lsoa_prac_pc %>%
  filter(!str_detect(LSOA_CODE, 'W|NO2011')) %>%
  inner_join(workforce_df, by=c("PRACTICE_CODE" = "PRAC_CODE", "YEAR" = "YEAR")) %>%
  mutate(
    YEAR = as.numeric(YEAR),
    TOTAL_GP_EXTGL_FTE = as.numeric(TOTAL_GP_EXTGL_FTE),
    TOTAL_GP_RET_FTE = as.numeric(TOTAL_GP_RET_FTE),
    pc_fte_gps = pc*(TOTAL_GP_EXTGL_FTE-TOTAL_GP_RET_FTE)
  ) %>%
  group_by(LSOA_CODE, YEAR) %>%
  summarise(gps_lsoa = sum(pc_fte_gps, na.rm=T)) %>%
  left_join(adj_pop_norm, by=c("LSOA_CODE"="LSOA_CODE", "YEAR"="YEAR")) %>%
  mutate(LSOA_DATE = case_when(YEAR %in% c(2017:2020) ~ 2011,
                               YEAR %in% c(2021:2023) ~ 2021)) %>%
  left_join(imd_2011_2021, by=c("LSOA_CODE"="LSOA_CODE", "LSOA_DATE"= "LSOA_DATE"))

workforce_imd <- attribute_gps_to_lsoa %>%
  group_by(IMD_QUINTILE, YEAR) %>%
  summarise(total_gps = sum(gps_lsoa, na.rm=T),
            total_population = sum(NEED_ADJ_POP, na.rm=T)) %>%
  mutate(gps_per_pop = 100000*total_gps/total_population) %>%
  na.omit()

write.csv(workforce_imd, "workforce.csv")

```

```{r load-imd}

## finance datasets
temp_finance <- list.files("data/payments", pattern = "\\.csv$", full.names = TRUE)

#for the time-series plots 
finance_datasets_timeseries <- lapply(temp_finance, function(file) {

  #get year from the csv names and set to 20XX
  year <- as.numeric(gsub(".*?([0-9]{2,4}).*", "\\1", file))
  
  #read in finance files and set columns to lowercase
  finances <- read.csv(file)
  names(finances) <- tolower(names(finances))

  #select and rename columns of interest
  columns <- list(
    PRACTICE_CODE = "practice.code",
    #CONTRACT_TYPE = "contract.type", #remove this for this - can add back in if want to choose contract type 
    WEIGHTED_PATIENTS = c("average.number.of.weighted.patients", 
                          "number.of.weighted.patients..last.known.figure.",
                          "average.number.of.weighted.patients1"),
    REGISTERED_PATIENTS = c("average.number.of.registered.patients", 
                            "number.of.registered.patients..last.known.figure.",
                            "average.number.of.registered.patients1"),
    PAYMENTS = "total.nhs.payments.to.general.practice",
    PAYMENTS_MINUS_DEDUCTIONS = c("total.nhs.payments.to.general.practice.minus.deductions","total.nhs.payments.to.general.practice.minus.deductions2"))

  #Check to see if columns with multiple options exist in the data, otherwise put as NA.
  get_col <- function(patterns) {
   match <- intersect(patterns, names(finances))
    if (length(match)) finances[[match[1]]] else rep(NA, nrow(finances))
  }
  
  # Ensure columns converted to numeric except for PC, CT and YEAR 
  df <- as.data.frame(lapply(columns, get_col)) %>%
    mutate(
     YEAR = 2000 + year,
     across(-any_of(c("PRACTICE_CODE", "CONTRACT_TYPE", "YEAR")))
  )
 
  df
})

#combine all dfs into one df 
finances_df_timeseries <- dplyr::bind_rows(finance_datasets_timeseries)

#for the year 23/24 barcharts
finance_datasets_barcharts <- lapply(temp_finance, function(file) {

  #get year from the csv names and set to 20XX
   year <- as.numeric(gsub(".*?([0-9]{2,4}).*", "\\1", file))
  if (year != 23) return(NULL)  # skip all files that aren't 2023
  
  #read in finance files and set columns to lowercase
  finances <- read.csv(file)
  names(finances) <- tolower(names(finances))

  #select and rename columns of interest
  columns <- list(
    PRACTICE_CODE = "practice.code",
    CONTRACT_TYPE = "contract.type",
    WEIGHTED_PATIENTS = "average.number.of.weighted.patients", 
    REGISTERED_PATIENTS = "average.number.of.registered.patients",
    PAYMENTS_MINUS_DEDUCTIONS = "total.nhs.payments.to.general.practice.minus.deductions",
    PAYMENTS = "total.nhs.payments.to.general.practice",
    TOTAL_COVID_PAYMENTS = "total.nhs.payments.to.general.practice.including.covid.vaccination..covid.support.and.long.covid.payments",
    PRESCRIBING_FEE = "prescribing.fee.payments",
    DISPENSING_FEE = "dispensing.fee.payments",
    REINBURSMENT_FEE = "reimbursement.of.drugs",
    OTHER_PAYMENTS = "other.payments",
    GLOBAL_SUM = "global.sum",
    MPIG = "mpig.correction.factor",
    IT = "information.management.and.technology",
    PMS_BALANCE = "balance.of.pms.expenditure",
    QOF_PAYMENT = "total.qof.payments",
    CHILD_VACCINE = "childhood.vaccination.and.immunisation.scheme",
    FLU_VACCINE = "influenza.and.pneumococcal.immunisations",
    ROTAVIRUS_VACCINE = "rotavirus.and.shingles.immunisation",
    PREMISES_PAYMENT = "premises.payments",
    COVID_IMMUN = "covid.immunisation",
    COVID_SUPPORT = "covid.support.and.expansion",
    LONG_COVID = "long.covid",
    GP_EXTENDED = "gp.extended.hours.access",
    LD = "learning.disabilities",
    MS = "minor.surgery",
    SFVP = "services.for.violent.patients",
    NDES = "non.des.item.pneumococcal.vaccine..childhood.immunisation.main.programme",
    OOAIHUC = "out.of.area.in.hours.urgent.care",
    MENINGITIS = "meningitis",
    PERTUSSIS = "pertussis",
    LIS = "local.incentive.schemes",
    WMS = "weight.management.service",
    MAR = "medical.assessment.reviews",
    SENIORITY = "seniority",
    DRSP = "doctors.retainer.scheme.payments",
    TLA = "total.locum.allowances",
    PCO = "pco.admin.other",
    GPT = "general.practice.transformation",
    WAF = "winter.access.fund",
    PSL = "prolonged.study.leave",
    AACIRL = "appraisal...appraiser.costs.in.respect.of.locums",
    PCNP = "pcn.participation"

  )

  #Check to see if columns with multiple options exist in the data, otherwise put as NA.
  get_col <- function(patterns) {
   match <- intersect(patterns, names(finances))
    if (length(match)) finances[[match[1]]] else rep(NA, nrow(finances))
  }
  
  # Ensure columns converted to numeric except for PC, CT and YEAR 
  df <- as.data.frame(lapply(columns, get_col)) %>%
    mutate(
     YEAR = 2000 + year,
     across(-any_of(c("PRACTICE_CODE", "CONTRACT_TYPE", "YEAR")))
  )
 
  df
})

#combine all dfs into one df 
finances_df_barchart <- dplyr::bind_rows(finance_datasets_barcharts)

```

```{r group columns}

#group columns into categories as defined in John Fords HEEC 
globalSum <- c("GLOBAL_SUM", "MPIG", "PMS_BALANCE")

ITPremises <- c("PREMISES_PAYMENT", "IT")

PCO <- c(
  "SENIORITY", "DRSP", "TLA", "PCO", "OTHER_PAYMENTS", "GPT", "PSL", "AACIRL",
  "PCNP", "WAF"
)

QOF <- c("QOF_PAYMENT")

#contractedServices <- c(
 # "CHILD_VACCINE", "GP_EXTENDED", "FLU_VACCINE", "LD",
 # "MS", "ROTAVIRUS_VACCINE", "SFVP", "OOAIHUC", "MENINGITIS", "PERTUSSIS", "LIS", "WMS", "MAR"
#)

DirectedEnhancedServices <- c(
  "CHILD_VACCINE", "FLU_VACCINE", "LD",
  "MS", "ROTAVIRUS_VACCINE", "SFVP", "OOAIHUC", "MENINGITIS", "PERTUSSIS", "WMS", "MAR"
)

LocalIncentiveSchemes <- c(
  "GP_EXTENDED","LIS"
)

COVID <- c("COVID_IMMUN", "COVID_SUPPORT", "LONG_COVID")

Prescribing <- c("PRESCRIBING_FEE", "DISPENSING_FEE", "REINBURSMENT_FEE")

#ensure covid columns are numeric
finances_df_barchart <- finances_df_barchart %>%
  mutate(across(any_of(COVID), as.numeric))

#calculate grouped totals 
finances_GROUPED_TOTAL <- finances_df_barchart %>%
  mutate(
    Total.Global.Sum          = rowSums(across(all_of(globalSum)), na.rm = TRUE),
    Total.IT.Premises         = rowSums(across(all_of(ITPremises)), na.rm = TRUE),
    Total.PCO                 = rowSums(across(all_of(PCO)), na.rm = TRUE),
    Total.DirectedEnhancedServices = rowSums(across(all_of(DirectedEnhancedServices)), na.rm = TRUE),
    Total.LocalIncentiveSchemes = rowSums(across(all_of(LocalIncentiveSchemes)), na.rm = TRUE),
    Total.Prescribing         = rowSums(across(all_of(Prescribing)), na.rm = TRUE),
    Total.COVID               = rowSums(across(all_of(COVID)), na.rm = TRUE)
  )

#join IMD onto and then group by year and imd, add the avg registered and weighted columns for each group as well 
finances_IMD_TOTAL <- finances_GROUPED_TOTAL %>%
  left_join(prac_imd, by = c("YEAR", "PRACTICE_CODE")) %>%
  filter(!is.na(IMD_QUINTILE)) %>%
  mutate(IMD_QUINTILE = as.factor(IMD_QUINTILE)) %>%
  group_by(IMD_QUINTILE, YEAR) %>%
  summarise(
    Global_Sum          = sum(Total.Global.Sum, na.rm = TRUE),
    IT_Premises         = sum(Total.IT.Premises, na.rm = TRUE),
    PCO_Payments        = sum(Total.PCO, na.rm = TRUE),
    Directed_Enhanced_Services = sum(Total.DirectedEnhancedServices, na.rm = TRUE),
    Local_Incentive_Schemes = sum(Total.LocalIncentiveSchemes, na.rm = TRUE),
    Prescribing         = sum(Total.Prescribing, na.rm = TRUE),
    COVID_19            = sum(Total.COVID, na.rm = TRUE),
    QOF                 = sum(QOF_PAYMENT, na.rm = TRUE),
    REGISTERED          = sum(REGISTERED_PATIENTS, na.rm = TRUE),
    WEIGHTED            = sum(WEIGHTED_PATIENTS, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(across(
    c(Global_Sum, IT_Premises, PCO_Payments, Directed_Enhanced_Services, Local_Incentive_Schemes, Prescribing, COVID_19, QOF),
    list(
      "Avg (Registered)" = ~ . / REGISTERED,
      "Avg (Weighted)"   = ~ . / WEIGHTED
    ),
    .names = "{.col} {fn}"
  ))

#pivot long
finances_IMD_TOTAL <- finances_IMD_TOTAL %>%
  pivot_longer(
    cols = -c(IMD_QUINTILE, YEAR),
    names_to = "Payment Category",
    values_to = "Total (£)"
  )


```



```{r load-imd}
#create dfs for time series total payments

#create weighted patients by year 
finance_imd_weighted <- finances_df_timeseries %>%
  left_join(prac_imd, by = c("YEAR", "PRACTICE_CODE")) %>%
  mutate(IMD_QUINTILE = as.factor(IMD_QUINTILE)) %>%
  group_by(IMD_QUINTILE, YEAR) %>%
  summarise(
    TOTAL_PAYMENTS = sum(
      PAYMENTS_MINUS_DEDUCTIONS,
      na.rm = TRUE
    ),
    TOTAL_WEIGHTED = sum(WEIGHTED_PATIENTS, na.rm = TRUE),
    NUM_PRACTICES = n_distinct(PRACTICE_CODE)
  ) %>%
  mutate(PAYMENT_PER_WEIGHTED_PATIENT = TOTAL_PAYMENTS / TOTAL_WEIGHTED)%>%
  na.omit()

#created registered patients by year
finance_imd_registered <- finances_df_timeseries %>%
  mutate(YEAR = as.numeric(YEAR),
         REGISTERED_PATIENTS = as.numeric(REGISTERED_PATIENTS),
         PAYMENTS = as.numeric(PAYMENTS)) %>%
  left_join(prac_imd, by=c("YEAR", "PRACTICE_CODE")) %>%
  mutate(IMD_QUINTILE = as.factor(IMD_QUINTILE)) %>%
  group_by(IMD_QUINTILE, YEAR) %>%
  summarise(TOTAL_PAYMENTS = sum(PAYMENTS_MINUS_DEDUCTIONS, na.rm=T),
            TOTAL_REGISTERED = sum(REGISTERED_PATIENTS, na.rm=T)) %>%
  mutate(PAYMENT_PER_REGISTERED_PATIENT = TOTAL_PAYMENTS/TOTAL_REGISTERED) %>%
  na.omit()

```

```{r myplot, fig.width=10, fig.height=6}

#create a uniform payment category column
finances_IMD_TOTAL <- finances_IMD_TOTAL %>%
  mutate(
    PayCat_base = str_trim(
      str_remove(`Payment Category`,
                 regex("\\((Registered|Weighted|ADJ)\\)$", ignore_case = TRUE))
    )
  )

#order levels for barplots
ordered_levels_avg <- c(
  "COVID_19 Avg",
  "Prescribing Avg",
  "Directed_Enhanced_Services Avg",
  "Local_Incentive_Schemes Avg",
  "PCO_Payments Avg",
  "QOF Avg",
  "IT_Premises Avg",
  "Global_Sum Avg"
)

ordered_levels_sum <- c(
  "COVID_19",
  "Prescribing",
  "Directed_Enhanced_Services",
  "Local_Incentive_Schemes",
  "PCO_Payments",
  "QOF",
  "IT_Premises",
  "Global_Sum"
)

Total_Finance_Categories <- finances_IMD_TOTAL %>%
  mutate(
    PayCat_base = factor(PayCat_base, levels = ordered_levels_sum)
  )

Avg_Finance_Categories <- finances_IMD_TOTAL %>%
  mutate(
    PayCat_base = factor(PayCat_base, levels = ordered_levels_avg)
  )

Weighted_By_Year <- ggplot(finance_imd_weighted, aes(
  x = YEAR,
  y = PAYMENT_PER_WEIGHTED_PATIENT,
  color = as.factor(IMD_QUINTILE),
  group = IMD_QUINTILE
  )) +
  geom_line(linewidth = 1) +
  geom_point(size = 2) +
  scale_color_brewer(palette = "Set1", name = "IMD Quintile") +
  scale_x_continuous(
    breaks = sort(unique(finance_imd_weighted$YEAR)),  
    labels = sort(unique(finance_imd_weighted$YEAR))
  ) +
  labs(
    title = "Payments per Weighted Patient by IMD Quintile",
    x = "Year",
    y = "Payment per Weighted Patient (£)"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "right",
    panel.grid.minor = element_blank(),
    strip.text = element_text(face = "bold")
  )

Registered_By_Year <- ggplot(finance_imd_registered, aes(
  x = YEAR,
  y = PAYMENT_PER_REGISTERED_PATIENT,
  color = as.factor(IMD_QUINTILE),
  group = IMD_QUINTILE
)) +
  geom_line(linewidth = 1) +
  geom_point(size = 2) +
  scale_color_brewer(palette = "Set1", name = "IMD Quintile") +
  scale_x_continuous(
    breaks = sort(unique(finance_imd_registered$YEAR)),  
    labels = sort(unique(finance_imd_registered$YEAR))
  ) +
  labs(
    title = "Payments per Registered Patient by IMD Quintile",
    x = "Year",
    y = "Payment per Registered Patient (£)"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "right",
    panel.grid.minor = element_blank(),
    strip.text = element_text(face = "bold")
  )


Total_Finance_Categories <- Total_Finance_Categories %>%
  filter(
    YEAR == 2023,
    !is.na(IMD_QUINTILE),
    !grepl("\\(Registered\\)|\\(Weighted\\)|\\(ADJ\\)", `Payment Category`, ignore.case = TRUE),
    !grepl("REGISTERED|WEIGHTED|adj_population|Total Population", `Payment Category`, ignore.case = TRUE)
  ) %>%
  group_by(`Payment Category`) %>%
  mutate(total_cat = sum(`Total (£)`, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(PayCat_base = factor(PayCat_base, levels = ordered_levels_sum)) %>%
  group_by(IMD_QUINTILE) %>%
  mutate(
    group_total = sum(`Total (£)`),
    pct = `Total (£)` / group_total,
    label_text = paste0(
  scales::percent(pct, accuracy = 1),
  " (",
  scales::label_number(
    accuracy = 0.1,          
    scale = 1e-6,            
    suffix = "m"
  )(`Total (£)`),
  ")"
)
  ) %>%
  ungroup()

Barchart_Total_Payments_By_Categories <- ggplot(Total_Finance_Categories, aes(
  x = as.factor(IMD_QUINTILE),
  y = `Total (£)`,
  fill =  PayCat_base
)) +
  geom_bar(stat = "identity") +
  geom_text(
    aes(label = label_text),
    size = 1.7,
    position = position_stack(vjust = 0.5),
    hjust = 0.5
  ) +
  scale_y_continuous(labels = scales::comma)+
  labs(
    title = "Total NHS Payments by IMD Quintile (2023)",
    x = "IMD Quintile (1 = Most Deprived, 5 = Least Deprived)",
    y = "Total Payments (£)"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "right",
    panel.grid.minor = element_blank(),
    axis.text.x = element_text(face = "bold"),
    plot.title = element_text(face = "bold", size = 16)
  )

Registered_Patients_Finance_Categories <- Avg_Finance_Categories %>%
  filter(
    YEAR == 2023,
    grepl("\\(Registered\\)$", `Payment Category`),  
    !is.na(IMD_QUINTILE)
  ) %>%
  mutate(PayCat_base = factor(PayCat_base, levels = ordered_levels_avg)) %>%
  group_by(IMD_QUINTILE) %>%
  mutate(
    group_total = sum(`Total (£)`),
    pct = `Total (£)` / group_total,
    label_text = paste0(
      scales::percent(pct, accuracy = 1), 
      " (", scales::comma(`Total (£)`, accuracy = 0.1), ")"
    )
  ) %>%
  ungroup()

Barchart_Registered_Patients_By_Categories <- ggplot(Registered_Patients_Finance_Categories, aes(
  x = IMD_QUINTILE,
  y = `Total (£)`,
  fill =  PayCat_base
)) +
  geom_bar(stat = "identity") +
  geom_text(
    aes(label = label_text),
    size = 1.7,
    position = position_stack(vjust = 0.5),
    hjust = 0.5
  ) +
  labs(
    title = "Average NHS Payments per Registered Patient by IMD Quintile (2023)",
    x = "IMD Quintile (1 = Most Deprived, 5 = Least Deprived)",
    y = "Average Payment per Registered Patient (£)"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "right",
    panel.grid.minor = element_blank(),
    axis.text.x = element_text(face = "bold"),
    plot.title = element_text(face = "bold", size = 16)
  )

Weighted_Patients_Finance_Categories <- Avg_Finance_Categories %>%
  filter(
    YEAR == 2023,
    grepl("\\(Weighted\\)$", `Payment Category`),
    !is.na(IMD_QUINTILE)
  ) %>%
  mutate(PayCat_base = factor(PayCat_base, levels = ordered_levels_avg)) %>%
  group_by(IMD_QUINTILE) %>%
  mutate(
    group_total = sum(`Total (£)`),
    pct = `Total (£)` / group_total,
    label_text = paste0(
      scales::percent(pct, accuracy = 1), 
      " (", scales::comma(`Total (£)`, accuracy = 0.1), ")"
    )
  ) %>%
  ungroup()

Barchart_Weighted_Patients_By_Categories <- ggplot(
  Weighted_Patients_Finance_Categories,
  aes(
    x = as.factor(IMD_QUINTILE),
    y = `Total (£)`,
    fill = PayCat_base
  )
) +
  geom_bar(stat = "identity") +
  geom_text(
    aes(label = label_text),
    size = 1.7,
    position = position_stack(vjust = 0.5),
    hjust = 0.5
  ) +
  labs(
    title = "Average NHS Payments per Weighted Patient by IMD Quintile (2023)",
    x = "IMD Quintile (1 = Most Deprived, 5 = Least Deprived)",
    y = "Average Payment per Weighted Patient (£)"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "right",
    panel.grid.minor = element_blank(),
    axis.text.x = element_text(face = "bold"),
    plot.title = element_text(face = "bold", size = 16)
  )

#print in Markdown
print(Weighted_By_Year)
print(Registered_By_Year)
#print(Adj_By_Year)
print(Barchart_Total_Payments_By_Categories)
print(Barchart_Registered_Patients_By_Categories)
print(Barchart_Weighted_Patients_By_Categories)
#print(Barchart_Adj_Patients_By_Categories)

#For ease to print into a PDF cleanly
# Create a list of all plots
plot_list <- list(
  Weighted_By_Year,
  Registered_By_Year,
 # Adj_By_Year,
  Barchart_Total_Payments_By_Categories,
  Barchart_Registered_Patients_By_Categories,
  Barchart_Weighted_Patients_By_Categories
  #Barchart_Adj_Patients_By_Categories
)

# Export all plots to a single PDF
pdf("All_NHS_IMD_Plots_Combined.pdf", width = 10, height = 6)

for (p in plot_list) {
  print(p)
}

dev.off()

message("Saved PDF")

```